### ISSUE TITLE
FE: Columns Dialogs

### ISSUE THREAD

**Issue by moffatethan** [hatchways/team-artistic-swimming#13]
\- Dialogs for creating and editing columns
\- New column dialog is triggered by hovering either side of the board

**Comment by Robertito1** [comment]
On a closer look at this story, I feel Cards should not have dialog box, the dialog box of a card should be opened when it wants to be edited, cards should be created under the it's column.
Please correct me if I'm wrong but if so the title of this issue is a bit misleading
